/**
 * Gallery image list.
 *
 * To add a photo:
 *   1. Put the image file in images/gallery/
 *   2. Add an entry to GALLERY_IMAGES (copy any line and update src / alt).
 */
window.GALLERY_IMAGES = [
  
  { src: "images/gallery/grad_walk.jpg", alt: "Layla on stage in purple graduation gown and cap making a heart shape with her hands at commencement" },
  { src: "images/gallery/260515 College of Integrated Science and Engineering Commencement - Rachel Holderman-1019_Original.jpg", alt: "Graduation cap decorated at JMU commencement" },
  { src: "images/gallery/layla grad 2026-33.JPEG", alt: "Layla in purple JMU graduation gown and gold stole standing outdoors" },
  { src: "images/gallery/layla grad 2026-34.JPEG", alt: "Layla smiling in purple graduation gown and white dress seated by a campus fountain" },
  { src: "images/gallery/layla and nate grad 2026-32.JPEG", alt: "Layla and friend in JMU graduation attire posing together outdoors" },
  { src: "images/gallery/hackathon.JPEG", alt: "Six teammates posing on stage in front of a Madison Make-A-Thon projection screen" },
  { src: "images/gallery/alumni_band.JPG", alt: "Layla and a friend in James Madison alumni Marching Royal Dukes jerseys on the football field" },
  { src: "images/gallery/05.jpg", alt: "Layla and a friend in JMU Pep Band shirts holding alto saxophones in stadium bleachers" },
  { src: "images/gallery/17.jpg", alt: "Layla smiling in a red shirt outdoors among autumn trees" },
  { src: "images/gallery/01.png", alt: "Layla crouching to pet a small white dog beside a black Audi sedan" },
  { src: "images/gallery/10.jpg", alt: "Rear view of a black Audi sedan and black Porsche 944 on a rooftop parking deck" },
  { src: "images/gallery/31.png", alt: "Front view of a black Porsche 944 and black Audi parked side by side outdoors" },
  { src: "images/gallery/24.jpg", alt: "Layla smiling outdoors in a green plaid flannel and jeans among fall leaves" },
  { src: "images/gallery/25.jpg", alt: "Six friends in life jackets jumping off a dock into a river" },
  { src: "images/gallery/42.jpg", alt: "Layla smiling in a mauve dress standing on a sidewalk in golden-hour light" },
  { src: "images/gallery/04.jpg", alt: "JMU Marching Royal Dukes performing in a European plaza with brass and percussion" },
  { src: "images/gallery/09.jpg", alt: "Marching band in purple uniforms performing on a football field with sousaphones and drumline" },
  { src: "images/gallery/26.jpg", alt: "Marching band snare drumline in white shirts lined up on a stadium field" },
  { src: "images/gallery/33.jpg", alt: "Layla playing snare drum in JMU marching band uniform at a night football game" },
  { src: "images/gallery/03.jpg", alt: "JMU Marching Royal Dukes drumline in purple uniforms performing with snare drums outdoors" },
  { src: "images/gallery/47.jpg", alt: "JMU drumline in pink shirts posing with purple snare drums on a football field at night" },
  { src: "images/gallery/37.jpg", alt: "JMU marching band members giving thumbs up in the rain wearing Beat Texas State pins" },
  { src: "images/gallery/45.jpg", alt: "Layla playing snare drum in JMU uniform at a stadium football game" },
  { src: "images/gallery/32.jpg", alt: "JMU marching band drumline in purple jerseys on a football field" },
  { src: "images/gallery/02.jpg", alt: "Layla in a JMU Drumline hoodie holding drumsticks over a purple snare drum" },
  { src: "images/gallery/40.jpg", alt: "Layla smiling outdoors in a black cropped sweater with autumn leaves in the background" },
  { src: "images/gallery/22.jpg", alt: "Layla in an indoor percussion jacket standing with a bass drum" },
  { src: "images/gallery/21.jpg", alt: "Forest Park High School marching band group photo on bleachers" },
  { src: "images/gallery/15.jpg", alt: "Layla playing a marching snare drum outdoors in a Pearl drum cover" },
  { src: "images/gallery/38.jpg", alt: "Concert ensemble in formal black attire wearing holiday headbands and face masks on stage" },
  { src: "images/gallery/36.jpg", alt: "Forest Park drumline members posing on stairs with tenor drums and snare" },
  { src: "images/gallery/11.jpg", alt: "Layla smiling while playing a marching snare drum in a purple basketball jersey" },
  { src: "images/gallery/34.jpg", alt: "Marching band drumline with bass drums on a field at sunset under stadium lights" },
  { src: "images/gallery/41.jpg", alt: "Collection of VEX robotics trophies and awards displayed" },
  { src: "images/gallery/23.jpg", alt: "Enginotic 6 robotics team posing at VEX Worlds with mentors" },
  { src: "images/gallery/20.jpg", alt: "Basement Robotics team in red World Championship hoodies wearing medals" },
  { src: "images/gallery/30.jpg", alt: "Enginotic 6 team at their VEX booth with trophies" },
  { src: "images/gallery/06.jpg", alt: "Enginotic 6 teams posing on stairs at a competition venue" },
  { src: "images/gallery/16.jpg", alt: "Team Enginotic 6 robotics students posing in their workshop in front of a whiteboard" },
  { src: "images/gallery/14.jpg", alt: "STEM camp group photo in a school library wearing matching STEMCAMP18 shirts" },
  { src: "images/gallery/43.jpg", alt: "Large group of students on stairs at VEX Worlds with team shirts and flags" },
  { src: "images/gallery/39.jpg", alt: "Basement Robotics team posing with a VEX trophy indoors" },
  { src: "images/gallery/46.png", alt: "Enginotic 6 drive team at VEX Worlds 2018 watching a match with controllers" },
  { src: "images/gallery/29.jpg", alt: "Robotics teams with trophies and robots in a gymnasium" },
  { src: "images/gallery/27.jpg", alt: "VEX IQ team smiling with a trophy in front of a VEX IQ Challenge banner" },
  { src: "images/gallery/28.jpg", alt: "Robotics teams posing with tri-fold presentation boards at a competition" },
  { src: "images/gallery/44.jpg", alt: "Graham Park Middle School robotics team posing with a VEX robot" },
  { src: "images/gallery/35.jpg", alt: "Triangle team 3615 winning the VEX IQ Amaze Award on arena screen and posing with trophy" },
  { src: "images/gallery/18.jpg", alt: "Triangle Elementary VEX IQ team holding an Excellence Award trophy" },
  { src: "images/gallery/19.png", alt: "Triangle robotics team kneeling with VEX IQ trophies and their robot" },
];
